image: ***REMOVED***/registry/docker:compose

docker-build-staging:
  stage: build
  before_script:
    - mkdir -p ~/.ssh
    - echo "$ID_RSA" > ~/.ssh/id_ed25519
    - chmod -R 700 ~/.ssh
    - ssh-keyscan $DEPLOY_SERVER >> ~/.ssh/known_hosts
    - ssh-keyscan $(getent hosts $DEPLOY_SERVER | cut -d' ' -f1) >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
  script:
    - export COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1
    - docker-compose -f docker-compose.stage.yml -p $STAGING_PROJECT_NAME pull
    - docker-compose -f docker-compose.stage.yml -p $STAGING_PROJECT_NAME build --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy --build-arg no_proxy=$no_proxy
    - docker-compose -f docker-compose.stage.yml -p $STAGING_PROJECT_NAME push
    - docker-compose -f docker-compose.stage.yml -p $STAGING_PROJECT_NAME -H "ssh://$DEPLOY_USER@$DEPLOY_SERVER" pull
    - docker-compose -f docker-compose.stage.yml -p $STAGING_PROJECT_NAME -H "ssh://$DEPLOY_USER@$DEPLOY_SERVER" down --remove-orphans
    - docker-compose -f docker-compose.stage.yml -p $STAGING_PROJECT_NAME -H "ssh://$DEPLOY_USER@$DEPLOY_SERVER" up -d
  only:
    - develop

docker-build-production:
  stage: build
  before_script:
    - mkdir -p ~/.ssh
    - echo "$ID_RSA" > ~/.ssh/id_ed25519
    - chmod -R 700 ~/.ssh
    - ssh-keyscan $DEPLOY_SERVER >> ~/.ssh/known_hosts
    - ssh-keyscan $(getent hosts $DEPLOY_SERVER | cut -d' ' -f1) >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
  script:
    - export COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1
    - docker-compose -f docker-compose.prod.yml -p $PRODUCTION_PROJECT_NAME pull
    - docker-compose -f docker-compose.prod.yml -p $PRODUCTION_PROJECT_NAME build --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy --build-arg no_proxy=$no_proxy
    - docker-compose -f docker-compose.prod.yml -p $PRODUCTION_PROJECT_NAME push
    - docker-compose -f docker-compose.prod.yml -p $PRODUCTION_PROJECT_NAME -H "ssh://$DEPLOY_USER@$DEPLOY_SERVER" pull
    - docker-compose -f docker-compose.prod.yml -p $PRODUCTION_PROJECT_NAME -H "ssh://$DEPLOY_USER@$DEPLOY_SERVER" down --remove-orphans
    - docker-compose -f docker-compose.prod.yml -p $PRODUCTION_PROJECT_NAME -H "ssh://$DEPLOY_USER@$DEPLOY_SERVER" up -d
  only:
    - master
