version: "3.9"

x-args: &args
  args:
    NODE_MAJOR: 14
    APP_ROOT: /app

x-env: &envs
  environment:
    - TZ=Asia/Krasnoyarsk
    - APP_ROOT=/app

x-common: &common
  restart: unless-stopped
  stdin_open: true
  tty: true

x-ui: &app
  build:
    <<: *args
    context: .
    dockerfile: .docker/Dockerfiles/app.dev.Dockerfile


x-frontend: &frontend
  <<: *envs
  <<: *app
  volumes:
    - .:/app
    - node_modules:/app/node_modules
  <<: *common

services:
  proc-ui-runner-dev:
    <<: *frontend
    container_name: proc-ui-runner-dev
    command: /bin/bash

  proc-ui-dev:
    <<: *frontend
    container_name: proc-ui-app-dev
    ports:
      - "4200:4200"
    command: ng serve --host 0.0.0.0 --disable-host-check --ssl=true --ssl-cert=/app/.docker/tls/***REMOVED***.crt --ssl-key=/app/.docker/tls/***REMOVED***.key

